# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.define 'box' do |box|
    box.vm.box = 'ubuntu/trusty64'
    box.vm.network :forwarded_port, guest: 80, host: 8080
    box.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "deploy.yml"
      ansible.groups = {
        "vagrant" => "box",
      }
    end
  end
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
end
