# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_create_debt_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtloan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
